# SVM & Naive Bayes | Assignment
# ---------------------------
# Question 1: What is a Support Vector Machine (SVM), and how does it work?
# ---------------------------
"""
Answer:
A Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks.
It works by finding the hyperplane that best separates data points of different classes with the maximum margin.
Support vectors are the data points closest to the hyperplane that influence its position.
"""

# ---------------------------
# Question 2: Explain the difference between Hard Margin and Soft Margin SVM.
# ---------------------------
"""
Answer:
- Hard Margin SVM: Assumes data is linearly separable and does not allow misclassification.
- Soft Margin SVM: Allows some misclassification to handle non-linearly separable or noisy data by introducing a penalty parameter C.
"""

# ---------------------------
# Question 3: What is the Kernel Trick in SVM? Give an example.
# ---------------------------
"""
Answer:
The Kernel Trick allows SVM to operate in a high-dimensional feature space without explicitly computing the coordinates.
Example: RBF (Radial Basis Function) kernel is commonly used for non-linear classification by mapping data into higher dimensions.
Use Case: Classifying data that is not linearly separable in the original space.
"""

# ---------------------------
# Question 4: What is a Naïve Bayes Classifier, and why is it called "naïve"?
# ---------------------------
"""
Answer:
A Naïve Bayes classifier is a probabilistic algorithm based on Bayes' Theorem.
It assumes that all features are independent of each other given the class label, which is why it's called "naïve".
"""

# ---------------------------
# Question 5: Describe Gaussian, Multinomial, and Bernoulli Naïve Bayes variants.
# ---------------------------
"""
Answer:
- Gaussian Naïve Bayes: Used for continuous data; assumes features follow a normal distribution.
- Multinomial Naïve Bayes: Used for discrete count data, e.g., word counts in text classification.
- Bernoulli Naïve Bayes: Used for binary/boolean features, e.g., presence/absence of words.
"""


# ---------------------------
###Question 6: Write a Python program to:


● Load the Iris dataset

● Train an SVM Classifier with a linear kernel

● Print the model's accuracy and support vectors
# ---------------------------

In [4]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

# Train SVM with linear kernel
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

# Accuracy and support vectors
y_pred = svm_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Support Vectors:\n", svm_model.support_vectors_)

Accuracy: 1.0
Support Vectors:
 [[4.8 3.4 1.9 0.2]
 [5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [5.6 3.  4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.  2.7 5.1 1.6]
 [6.3 2.5 4.9 1.5]
 [6.1 2.9 4.7 1.4]
 [6.5 2.8 4.6 1.5]
 [6.9 3.1 4.9 1.5]
 [6.3 2.3 4.4 1.3]
 [6.3 2.5 5.  1.9]
 [6.3 2.8 5.1 1.5]
 [6.3 2.7 4.9 1.8]
 [6.  3.  4.8 1.8]
 [6.  2.2 5.  1.5]
 [6.2 2.8 4.8 1.8]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [5.6 2.8 4.9 2. ]
 [5.9 3.  5.1 1.8]
 [4.9 2.5 4.5 1.7]]


# ---------------------------
###Question 7: Write a Python program to:
● Load the Breast Cancer dataset

● Train a Gaussian Naïve Bayes model

● Print its classification report including precision, recall, and F1-score.

# ---------------------------

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

# Load dataset
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.2, random_state=42)

# Train Gaussian Naïve Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Predictions and report
y_pred = gnb.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        43
           1       0.96      1.00      0.98        71

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



# ---------------------------
###Question 8: Write a Python program to:
● Train an SVM Classifier on the Wine dataset using GridSearchCV to find the best C and gamma.

● Print the best hyperparameters and accuracy.
# ---------------------------

In [6]:
from sklearn.datasets import load_wine
from sklearn.model_selection import GridSearchCV

wine = load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=42)

# GridSearch for best C and gamma
param_grid = {'C':[0.1,1,10], 'gamma':[0.01,0.1,1], 'kernel':['rbf']}
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best Hyperparameters:", grid.best_params_)
print("Accuracy:", grid.best_score_)

Best Hyperparameters: {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
Accuracy: 0.6189655172413794


# ---------------------------
###Question 9: Write a Python program to:
● Train a Naïve Bayes Classifier on a synthetic text dataset (e.g. using sklearn.datasets.fetch_20newsgroups).

● Print the model's ROC-AUC score for its predictions.
# ---------------------------

In [7]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import label_binarize

# Load dataset
categories = ['alt.atheism', 'sci.space']
news = fetch_20newsgroups(subset='train', categories=categories)
X = news.data
y = news.target

# Vectorize text
vectorizer = TfidfVectorizer()
X_vect = vectorizer.fit_transform(X)

# Train Multinomial Naïve Bayes
mnb = MultinomialNB()
mnb.fit(X_vect, y)

# ROC-AUC score
y_test_bin = label_binarize(y, classes=[0,1])
y_pred_prob = mnb.predict_proba(X_vect)[:,1]
print("ROC-AUC Score:", roc_auc_score(y_test_bin, y_pred_prob))

ROC-AUC Score: 0.9999929735806633


# ---------------------------
###Question 10: Imagine you’re working as a data scientist for a company that handles email communications.

####Your task is to automatically classify emails as Spam or Not Spam. The emails may contain:

● Text with diverse vocabulary

● Potential class imbalance (far more legitimate emails than spam)

● Some incomplete or missing data

####Explain the approach you would take to:

● Preprocess the data (e.g. text vectorization, handling missing data)

● Choose and justify an appropriate model (SVM vs. Naïve Bayes)

● Address class imbalance

● Evaluate the performance of your solution with suitable metrics And explain the business impact of your solution.

# ---------------------------

##Answer

# Spam Email Classification

Imagine you’re working as a data scientist for a company that handles email communications. The task is to automatically classify emails as Spam or Not Spam.

---

## Step 1: Data Preprocessing
- Handle missing values
- Text cleaning (lowercasing, remove punctuation)
- Text vectorization using TF-IDF


In [1]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample dataset
data = pd.DataFrame({
    'email': ["Free money!!!", "Meeting tomorrow", np.nan, "Limited offer just for you", "Project update attached"],
    'label': [1, 0, 0, 1, 0]  # 1 = Spam, 0 = Not Spam
})

# Handle missing values
data = data.dropna(subset=['email'])

# Text vectorization using TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['email'])
y = data['label']

print("Feature matrix shape:", X.shape)

Feature matrix shape: (4, 12)


## Step 2: Model Selection
- **Naïve Bayes** is preferred for text classification due to speed and probabilistic output.
- **SVM** is an alternative but slower for large datasets.
- We'll use Multinomial Naïve Bayes here.


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train Multinomial Naïve Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)[:,1]


## Step 3: Handle Class Imbalance
- Techniques: class weights, oversampling, undersampling
- For small dataset example, we'll proceed with evaluation metrics


In [ ]:
from sklearn.metrics import classification_report, roc_auc_score

# Evaluate model performance
print("Classification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_pred_prob))


## Step 4: Evaluation Metrics
- **Accuracy**: Overall correctness  
- **Precision**: Correctly predicted spam / All predicted spam  
- **Recall**: Correctly predicted spam / All actual spam  
- **F1-score**: Balance of precision and recall  
- **ROC-AUC**: Measures model's ability to distinguish classes  

---

## Step 5: Business Impact
- Automates spam filtering, reducing manual effort  
- Improves email security by detecting phishing/malicious emails  
- Ensures important emails are not lost  
- Scalable for large email volumes
